
### 조직 등록
POST localhost:8092/v1/tenants
Content-Type: application/json
X-USER-ID: e4cb2550-d93c-4627-968d-fdfd113da28d

{
  "name": "test new",
  "description": "most pleasure tenant",
  "canHaveGateway": true,
  "privateGatewayUp": false,
  "privateGatewayDown": false,
  "maxGatewayCount": 0,
  "maxDeviceCount": 0,
  "ip": "111.111.111.111"
}

### 회원가입
POST localhost:8092/user
Content-Type: application/json

{
  "email": "asdf@micro.com",
  "username": "asdf",
  "password": "asdf",
  "provider": "google"
}

### 유저 단일 조회
GET localhost:8092/user?email=test@test.com
Content-Type: application/json


### 사용자가 속한 조직 리스트 조회
GET localhost:8092/v1/tenants
Content-Type: application/json
X-USER-ID: e4cb2550-d93c-4627-968d-fdfd113da28d

### one tenant test
GET localhost:8092/v1/tenant/4b81666b-acca-451a-9a52-cecb931f1f7d?page=0&size=3
Content-Type: application/json
X-USER-ID: 05244f12-6daf-4e1f-8315-c66783a0ab56