server:
  port: 8092

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

chirpstack:
  host:
  admin:
    api:

logging:
  level:
    root: info

minio:
  url:
    internal: http://localhost:9000
    external: http://localhost:9000
  access-key: JuOZZWJpYvkhJDeiUZ4a
  secret-key: UpcNt6zRdswxQlrOot5iAeVU9Lh1Y8TKKEwgYr4T
