server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/iot_iotify
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 296

chirpstack:
  host: ${CHIRPSTACK_HOST}
  admin:
    api: ${CHIRPSTACK_API_KEY}

logging:
  level:
    root: debug


minio:
  url: ${}
  access-key: ${}
  secret-key: ${}